### ISSUE TITLE
Need good sample test app for new SQLAlchemy Users. Here's what I tried and didn't work.

### ISSUE THREAD

**Issue by richardschoen** [IBM/sqlalchemy-ibmi#103]
This demo app was run in bash after sqlalchamy-ibmi was installed. (V7R3)

```
CREATE COLLECTION PYDEMO1 WITH DATA DICTIONARY                  
```
***Schema PYDEMO1 created.***
                     
```
CREATE TABLE PYDEMO1/DEMOTBL1 (LAST CHAR (50 ) NOT NULL WITH    
DEFAULT, FIRST CHAR (50 ) NOT NULL WITH DEFAULT)                
```
***Table DEMOTBL1 created in PYDEMO1.***

Python sample:

```
import sqlalchemy as sa

engine = sa.create_engine("ibmi://IBMIUSER1:IBMIPASS1@localhost")

cnxn = engine.connect()
metadata = sa.MetaData()
table = sa.Table('PYDEMO1.DEMOTBL1', metadata, autoload=True, autoload_with=engine)

query = sa.select([table])

result = cnxn.execute(query)
result = result.fetchall()

# print first entry
print(result[0])
```

Python sample fails with:

```
Traceback (most recent call last):
  File "pysqlalchemytest1.py", line 24, in <module>
    table = sa.Table('PYDEMO1.DEMOTBL1', metadata, autoload=True, autoload_with=engine)
  File "<string>", line 2, in __new__
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 559, in __new__
    metadata._remove_table(name, schema)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 554, in __new__
    table._init(name, metadata, *args, **kw)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 648, in _init
    resolve_fks=resolve_fks,
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 672, in _autoload
    _extend_on=_extend_on,
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2221, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1660, in run_callable
    return callable_(self, *args, **kwargs)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 467, in reflecttable
    table, include_columns, exclude_columns, resolve_fks, **opts
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 679, in reflecttable
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: PYDEMO1.DEMOTBL1
```

**Comment by kadler** [comment]
Try `table = sa.Table('DEMOTBL1', metadata, autoload=True, autoload_with=engine, schema='PYDEMO1')`

**Comment by richardschoen** [comment]
Yep, that did it. Thanks.

**Comment by kadler** [comment]
Reoening as we should have the examples in the repo

**Comment by naveen-ram** [comment]
samples are [here](https://github.com/IBM/sqlalchemy-ibmi/tree/master/samples)
