### ISSUE TITLE
Superset with SQLALCHEMY_IBMI : cannot import name 'Row' from 'sqlalchemy.engine'

### ISSUE THREAD

**Issue by rh-igs** [IBM/sqlalchemy-ibmi#146]
I have added Sqlalchemy_ibmi to Docker/requirements-local.txt

Now i get the following Error in superset:

2023-06-27 15:04:50 Init Step 1/4 [Starting] -- Applying DB migrations
2023-06-27 15:04:50 
2023-06-27 15:04:50 
2023-06-27 15:04:50 ######################################################################
2023-06-27 15:04:50 
2023-06-27 15:04:53 Traceback (most recent call last):
2023-06-27 15:04:53   File "/usr/local/bin/superset", line 33, in <module>
2023-06-27 15:04:53     sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
2023-06-27 15:04:53   File "/usr/local/bin/superset", line 25, in importlib_load_entry_point
2023-06-27 15:04:53     return next(matches).load()
2023-06-27 15:04:53   File "/usr/local/lib/python3.9/importlib/metadata.py", line 86, in load
2023-06-27 15:04:53     module = import_module(match.group('module'))
2023-06-27 15:04:53   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2023-06-27 15:04:53     return _bootstrap._gcd_import(name[level:], package, level)
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2023-06-27 15:04:53   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2023-06-27 15:04:53   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-06-27 15:04:53   File "/app/superset/__init__.py", line 21, in <module>
2023-06-27 15:04:53     from superset.app import create_app
2023-06-27 15:04:53   File "/app/superset/app.py", line 23, in <module>
2023-06-27 15:04:53     from superset.initialization import SupersetAppInitializer
2023-06-27 15:04:53   File "/app/superset/initialization/__init__.py", line 33, in <module>
2023-06-27 15:04:53     from superset.extensions import (
2023-06-27 15:04:53   File "/app/superset/extensions/__init__.py", line 34, in <module>
2023-06-27 15:04:53     from superset.utils.encrypt import EncryptedFieldFactory
2023-06-27 15:04:53   File "/app/superset/utils/encrypt.py", line 24, in <module>
2023-06-27 15:04:53     from sqlalchemy.engine import Connection, Dialect, Row
2023-06-27 15:04:53 ImportError: cannot import name 'Row' from 'sqlalchemy.engine' (/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/__init__.py)

I have installed Sqlalchemy Version 2.0.17 and Sqlalchemy_ibmi Version 0.9.2

In python i can connect to my IBMi with ibmi://user:password@hostname

**Comment by kadler** [comment]
sqlalchemy-ibmi doesn't yet support SQLAlchemy 2.0

**Comment by kadler** [comment]
Please try again with SQLAlchemy 1.4 and sqlalchemy-ibmi 0.9.3
