### ISSUE TITLE
pytest 5.4 causes issues with SQLAlchemy

### ISSUE THREAD

**Issue by kadler** [IBM/sqlalchemy-ibmi#60]
I get this error when using pytest 5.4.1:
```
============================= test session starts ==============================
platform *** -- Python 3.7.6, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /opt/hostedtoolcache/Python/3.7.6/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/sqlalchemy-ibmi/sqlalchemy-ibmi, inifile: setup.cfg
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
_____________________ ERROR collecting test/test_suite.py ______________________
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>

    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/_pytest/python.py", line 216, in pytest_pycollect_makeitem
    res = outcome.get_result()
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/sqlalchemy/testing/plugin/pytestplugin.py", line 195, in pytest_pycollect_makeitem
    for parametrize_cls in _parametrize_cls(collector.module, obj)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/sqlalchemy/testing/plugin/pytestplugin.py", line 195, in <listcomp>
    for parametrize_cls in _parametrize_cls(collector.module, obj)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/_pytest/nodes.py", line 83, in __call__
    warnings.warn(NODE_USE_FROM_PARENT.format(name=self.__name__), stacklevel=2)
pytest.PytestDeprecationWarning: direct construction of Class has been deprecated, please use Class.from_parent
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.20s ===============================
```

Using pytest 5.3.5 does not cause this error. Seems to be some problem with SQLAlchemy's test suite.

**Comment by kadler** [comment]
Closed by #75
